@host = http://localhost:5080

### Service info
GET {{host}}/

### Health
GET {{host}}/health

### Search locations
GET {{host}}/api/v1/locations?countryCode=IN

### Create location
POST {{host}}/api/v1/locations
Content-Type: application/json

{
  "name": "Udaipur",
  "city": "Udaipur",
  "country": "India",
  "countryCode": "IN",
  "latitude": 24.5854,
  "longitude": 73.7125,
  "type": "City",
  "region": "Rajasthan",
  "description": "City of Lakes",
  "timezone": "Asia/Kolkata"
}
