name: Trigger auto deployment for location-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/location-service-AutoDeployTrigger-1b82b4ec-b627-4c9f-bb2e-48037f4a6a7e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.LOCATIONSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LOCATIONSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LOCATIONSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: tripalaahacr.azurecr.io
          registryUsername: ${{ secrets.LOCATIONSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LOCATIONSERVICE_REGISTRY_PASSWORD }}
          containerAppName: location-service
          resourceGroup: tripwalaah-location-microservice
          imageToBuild: tripalaahacr.azurecr.io/location-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


